### ISSUE TITLE
java.net.SocketException: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by Danbown** [Blazemeter/CorrelationsRecorderTemplates#2]
Hi
sadly not able to record any traffic with plugin. Regular 'Test Script Recorder' works fine but Correlation Recorder gives following error in the logs and nothing is recorded. I hope this is recording locally only and not trying to write elsewhere?

```java
2022-09-21 16:43:01,769 WARN o.a.j.p.h.p.Proxy: [63167]  Exception while writing error
java.net.SocketException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[?:?]
	at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
	at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
	at java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
	at sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1298) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1257) ~[?:?]
	at java.io.DataOutputStream.writeBytes(DataOutputStream.java:282) ~[?:?]
	at org.apache.jmeter.protocol.http.proxy.Proxy.writeErrorToClient(Proxy.java:592) ~[ApacheJMeter_http.jar:5.5]
	at org.apache.jmeter.protocol.http.proxy.Proxy.run(Proxy.java:268) ~[ApacheJMeter_http.jar:5.5]
	at com.blazemeter.jmeter.correlation.core.proxy.CorrelationProxy.run(CorrelationProxy.java:53) ~[jmeter-bzm-correlation-recorder-1.2.jar:?]

**Comment by RicardoPoleo** [comment]
Hello @Danbown,

Thanks for bringing this up. Maybe you are talking about the [JMeter's Plugin for the Correlation Recorder](https://github.com/Blazemeter/CorrelationRecorder) and not the [Plugin's Central Repository](https://github.com/Blazemeter/CorrelationsRecorderTemplates)? 

If it's related to the Plugin, I would recommend you:

1. Check if this issue has already been reported by other users in the [Plugin's Repository](https://github.com/Blazemeter/CorrelationRecorder), since this is not the right repo for this kind of matters.
2. Create an issue there, in case this error has not been reported yet.
3. Provide as much information as you can regarding your environment (What versions of both the Plugin and JMeter you are using, does this occur on windows/Unix machine, what version of Java are you using to run JMeter, etc)
4. Last, but not least, give us some details regarding the whole issue, so we can narrow down the problem that you are facing.

At any rate, I'll close this issue, since it doesn't appears to be related to the Correlation Rules and the Central Repository in particular.

Hope you have a nice day,

**Comment by Danbown** [comment]
Thanks @RicardoPoleo for your helpful reply - apologies, I am indeed in the wrong place but will search in the repo suggested and post if necessary. Regards, Dan
